pipeline {

    environment {
        // Git Repository Information
        GITHUP_ID = "doogee323"
        GIT_URL = "https://github.com/${GITHUP_ID}/tz-demo-app.git"
        GIT_BRANCH = "vagrant"
        GIT_COMMITTER_EMAIL = "doogee323@gmail.com"

        // Docker and Application Configuration
        BUILD_NUMBER = "${env.BUILD_NUMBER}"
        DOCKER_NAME = "tz-demo-app"
        APP_NAME = "tz-demo-app"
        NAMESPACE = "devops"
        K8S_SOURCE = "${env.BRANCH_NAME == "main" ? "k8s.yaml" : env.BRANCH_NAME == "qa" ? "k8s-qa.yaml" : "k8s-dev.yaml"}"
        STAGING = "${env.BRANCH_NAME == "main" ? "prod" : env.BRANCH_NAME == "qa" ? "qa" : "dev"}"
        NODE_ENV = "development"
        K8S_FILE = "k8s.yaml"
        USE_ARGOCD = "true"

        // Kubernetes Configuration
        DOMAIN = "topzone.me"
        CLUSTER_NAME = "topzone-k8s"
        CERTIFICATE="aaaaaa"

        KUBECTL = "kubectl -n ${NAMESPACE} --kubeconfig /var/lib/jenkins/.kube/tz_${CLUSTER_NAME}"

        GIT_CREDENTIAL = 'github-token'
        GITHUP_TOKEN = credentials('GITHUP_TOKEN')
        VAULT_TOKEN = credentials('VAULT_TOKEN')
        ARGOCD_ID = "admin"
        ARGOCD_PASSWORD = "DevOps!323"

        WORKSPACE= "/home/jenkins/agent/workspace/${APP_NAME}"
        REPOSITORY_TAG = "harbor.harbor.${CLUSTER_NAME}.${DOMAIN}/${CLUSTER_NAME}/${DOCKER_NAME}:${BUILD_NUMBER}"
        DOCKER_PASSWORD = credentials('DOCKER_PASSWORD')
    }

    agent {
        kubernetes {
            defaultContainer "devops2"
            yaml """
apiVersion: v1
kind: Pod
metadata:
  name: devopsBuild
spec:
  hostAliases:
  - ip: "192.168.86.200"
    hostnames:
    - "harbor.harbor.topzone-k8s.topzone.me"
  serviceAccountName: jenkins
  containers:
  - name: devops2
    image: topzone8713/devops-utils2:latest
    resources:
      requests:
        memory: 200Mi
        cpu: "200m"
      limits:
        memory: 1Gi
        cpu: "300m"
    tty: true
    command: ["sleep"]
    args: ["99d"]
    volumeMounts:
      - name: shared-data
        mountPath: /root/shared-data

  - name: kaniko2
    image: gcr.io/kaniko-project/executor:v1.7.0-debug
    imagePullPolicy: Always
    resources:
      requests:
        memory: 200Mi
        cpu: "200m"
      limits:
        memory: 1Gi
        cpu: "300m"
    tty: true
    command: ["sleep"]
    args: ["99d"]
    volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker
      - name: shared-data
        mountPath: /root/shared-data
  restartPolicy: Never
  volumes:
    - name: docker-config
      secret:
        secretName: harbor-registry-secret
    - name: shared-data
      emptyDir: {}
            """
        }
    }

    stages {
       stage("Setup Git Safe Directory") {
            steps {
                sh """
                git config --global --add safe.directory ${WORKSPACE}
                """
            }
        }
        stage("Git SCM") {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: GIT_BRANCH]],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [],
                    userRemoteConfigs: [[
                        url: GIT_URL,
                        credentialsId: GIT_CREDENTIAL
                    ]]
                ])
            }
        }

        stage('Prep') {
            steps {
                container("devops2") {
                    script {
                        sh """
                        rm -rf ./${K8S_FILE}
                        cp -Rp k8s/${K8S_SOURCE} ./${K8S_FILE}
                        cp -Rp /home/jenkins/agent/workspace/${DOCKER_NAME} /root/shared-data/${DOCKER_NAME}
                        bash ./k8s/k8s.sh vault_config devops-dev/tz-demo-app
                        cp -Rf .env /root/shared-data/tz-demo-app/.env
                        """
                    }
                }
            }
        }

        stage('Building & Pushing') {
            parallel {
                stage("Build and Push images") {
                    steps {
                        container("kaniko2") {
                            script {
                                sh """
                                /kaniko/executor --dockerfile=Dockerfile --context=/root/shared-data/${DOCKER_NAME} --build-arg NODE_ENV=${NODE_ENV} \
                                    --destination=${REPOSITORY_TAG} --use-new-run --cleanup --force --skip-tls-verify
                                """
                            }
                        }
                    }
                }
            }
        }

        stage('Deploy the service to Cluster') {
            steps {
                container("devops2") {
                    sh """
                    bash ./k8s/k8s.sh apply
                    """
                }
            }
        }
    }

    post {
        always {
            script {
                env.GIT_COMMIT_MSG = sh(script: 'git log -1 --pretty=%B ${GIT_COMMIT}', returnStdout: true).trim()
                env.GIT_AUTHOR = sh(script: 'git log -1 --pretty=%cn ${GIT_COMMIT}', returnStdout: true).trim()
                env.GIT_COMMIT_EMAIL = sh(script: 'git log --format="%ae" | head -1', returnStdout: true).trim()
            }
            emailext(
                subject: "Jenkins Build ${currentBuild.currentResult}: Job ${env.JOB_NAME} ( ${GIT_AUTHOR} )",
                body: """
                    <p> Build on Job:
                    <a style = "font-size:14px;text-decoration:underline;font-weight:bold" href="${env.BUILD_URL}/console">
                    ${currentBuild.fullDisplayName}</a></p>
                    <p>
                        ${env.GIT_COMMIT_MSG}
                    </p
                    <p>
                    </p>
                """
                , mimeType: 'text/html'
                , attachLog: true
                , to: "${GIT_COMMIT_EMAIL}"
            )
        }
    }
}


